name: 📝 Comment on Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      package_version_to_follow:
        required: true
        type: string
      release_branch:
        required: true
        type: string

jobs:
  comment:
    name: Comment on Release
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 📝 Comment on issues
        working-directory: ./scripts/release
        run: node ./comment.mjs
        env:
          PACKAGE_VERSION_TO_FOLLOW: ${{ inputs.package_version_to_follow }}
